package myerrors

import "errors"

var (
	AIRDROP_NEED_LIKE_POST        = errors.New("AIRDROP_NEED_LIKE_POST")
	AIRDROP_NEED_COMMENT_POST     = errors.New("AIRDROP_NEED_COMMENT_POST")
	AIRDROP_NEED_SHARE_PORT       = errors.New("AIRDROP_NEED_SHARE_PORT")
	AIRDROP_PROGRAM_EXPIRED       = errors.New("AIRDROP_PROGRAM_EXPIRED")
	AIRDROP_PROGRAM_NOT_START_YET = errors.New("AIRDROP_PROGRAM_NOT_START_YET")
	AIRDROP_PROGRAM_INSUFFICIENT  = errors.New("AIRDROP_PROGRAM_INSUFFICIENT")
	AIRDROP_PHONE_UN_VERIFIED     = errors.New("AIRDROP_PHONE_UN_VERIFIED")
	AIRDROP_RECEIVED              = errors.New("AIRDROP_RECEIVED")
)
